# fly.toml generated for kht-crm
app = "kht-crm"
primary_region = "sin"

[build]
  # Bạn có thể thêm dockerfile nếu muốn
  # dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000   # NestJS default port, Fly sẽ map PORT env variable
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
